/* Conteúdo A1 separado da interface para facilitar revisão pedagógica. */
const A1_LESSONS = [
  ['greetings','Greetings and Introductions','Cumprimentar, apresentar-se e encerrar uma conversa.',['hello|olá|heh-LOH|Hello, I am Mia.','hi|oi|hai|Hi, how are you?','name|nome|neim|My name is Leo.','meet|conhecer|miit|Nice to meet you.','please|por favor|pliiz|Please, sit down.','thanks|obrigado(a)|thænks|Thanks for your help.','goodbye|tchau|gud-BAI|Goodbye, see you soon.','welcome|bem-vindo(a)|WEL-kam|Welcome to our class.'],['How are you?','Nice to meet you.','See you tomorrow.']],
  ['personal','Personal Information','Perguntar e responder informações pessoais básicas.',['address|endereço|a-DRES|My address is Pine Street.','country|país|KAN-tri|Brazil is my country.','city|cidade|SI-ti|I live in a big city.','phone|telefone|foun|My phone is new.','email|e-mail|II-meil|What is your email?','live|morar|liv|I live in Recife.','from|de/origem|fram|I am from Brazil.','single|solteiro(a)|SING-gal|She is single.'],['Where are you from?','What is your phone number?','I live near here.']],
  ['numbers','Numbers and Age','Usar números para informar idade, telefone e quantidades.',['one|um|wan|I have one brother.','two|dois|tuu|Two coffees, please.','ten|dez|ten|She is ten years old.','twenty|vinte|TWEN-ti|It costs twenty dollars.','hundred|cem|HAN-drəd|One hundred people are here.','age|idade|eidj|What is your age?','old|velho/idade|ould|I am eighteen years old.','number|número|NAM-bər|Write your number here.'],['How old are you?','My number is twenty-four.','I need two tickets.']],
  ['family','Family and Friends','Descrever família, amigos e relações próximas.',['mother|mãe|MA-dhər|My mother is kind.','father|pai|FA-dhər|His father is tall.','sister|irmã|SIS-tər|This is my sister.','brother|irmão|BRA-dhər|Her brother is funny.','parents|pais|PE-rənts|My parents live nearby.','friend|amigo(a)|frend|Sara is my friend.','husband|marido|HAZ-bənd|Her husband is a doctor.','children|filhos/crianças|TCHIL-drən|They have two children.'],['This is my best friend.','Do you have siblings?','My family is small.']],
  ['routine','Daily Routine','Falar sobre hábitos e ações do dia a dia.',['wake up|acordar|weik ap|I wake up at seven.','shower|banho|SHAU-ər|I take a shower.','breakfast|café da manhã|BREK-fəst|We eat breakfast early.','work|trabalhar|wərk|I work from home.','study|estudar|STA-di|They study English daily.','lunch|almoço|lantch|Lunch is at noon.','exercise|exercitar-se|EK-sər-saiz|I exercise after work.','sleep|dormir|sliip|The baby sleeps well.'],['I get up at seven.','I work every weekday.','What time do you sleep?']],
  ['time','Time and Schedules','Informar horas e combinar compromissos.',['clock|relógio|klak|The clock is slow.','morning|manhã|MOR-ning|See you in the morning.','afternoon|tarde|af-tər-NUUN|I work this afternoon.','evening|noite|II-vning|Good evening, everyone.','today|hoje|tə-DEI|I am busy today.','tomorrow|amanhã|tə-MA-rou|The class is tomorrow.','early|cedo|ER-li|We arrived early.','late|atrasado/tarde|leit|The bus is late.'],['What time is the meeting?','Are you free tomorrow?','It starts at half past nine.']],
  ['food','Food and Drinks','Nomear alimentos e expressar preferências.',['bread|pão|bred|The bread is fresh.','rice|arroz|rais|I eat rice at lunch.','water|água|WO-tər|Can I have water?','coffee|café|KA-fi|This coffee is hot.','fruit|fruta|fruut|Fruit is a healthy snack.','vegetables|vegetais|VEJ-tə-bəls|We need more vegetables.','hungry|com fome|HANG-gri|I am very hungry.','thirsty|com sede|THER-sti|Are you thirsty?'],['I would like some water.','I do not eat meat.','What is your favorite food?']],
  ['restaurant','At a Restaurant','Fazer pedidos e interagir em um restaurante.',['menu|cardápio|MEN-yu|May I see the menu?','order|pedido/pedir|OR-dər|We are ready to order.','waiter|garçom|WEI-tər|The waiter is helpful.','bill|conta|bil|Can I have the bill?','table|mesa|TEI-bəl|A table for two, please.','delicious|delicioso|di-LI-shəs|The soup is delicious.','starter|entrada|STAR-tər|Salad is my starter.','dessert|sobremesa|di-ZERT|Chocolate cake for dessert.'],['A table for two, please.','Could I have the bill?','I would like the soup.']],
  ['home','Home and Furniture','Descrever cômodos, móveis e localização de objetos.',['house|casa|haus|My house is small.','kitchen|cozinha|KI-tchən|We cook in the kitchen.','bedroom|quarto|BED-ruum|The bedroom is upstairs.','bathroom|banheiro|BATH-ruum|Where is the bathroom?','chair|cadeira|tcher|Sit on this chair.','sofa|sofá|SOU-fa|The sofa is comfortable.','window|janela|WIN-dou|Open the window, please.','door|porta|dor|Close the door quietly.'],['The keys are on the table.','There are two bedrooms.','Make yourself at home.']],
  ['town','Places in Town','Localizar lugares e pedir direções simples.',['bank|banco|bænk|The bank closes at four.','hospital|hospital|HAS-pi-təl|The hospital is nearby.','station|estação|STEI-shən|Meet me at the station.','market|mercado|MAR-kit|The market opens early.','school|escola|skuul|The school is across the street.','park|parque|park|We walk in the park.','left|esquerda|left|Turn left at the bank.','right|direita|rait|The cafe is on your right.'],['How do I get to the station?','Turn left at the corner.','Is there a bank near here?']],
  ['shopping','Shopping and Prices','Perguntar preços, tamanhos e realizar compras.',['price|preço|prais|What is the price?','cheap|barato|tchiip|This bag is cheap.','expensive|caro|ik-SPEN-siv|That coat is expensive.','size|tamanho|saiz|What size do you need?','cash|dinheiro|kæsh|I can pay in cash.','card|cartão|kard|Do you accept cards?','change|troco|tcheindj|Keep the change.','receipt|recibo|ri-SIIT|Here is your receipt.'],['How much is this?','Do you have a smaller size?','Can I pay by card?']],
  ['work','Work and Occupations','Falar sobre profissões e ambiente de trabalho.',['teacher|professor(a)|TII-tchər|My teacher is patient.','doctor|médico(a)|DAK-tər|The doctor works here.','engineer|engenheiro(a)|en-jə-NIR|She is an engineer.','office|escritório|A-fis|Our office is downtown.','job|emprego|djab|I like my job.','manager|gerente|MÆ-ni-jər|Ask the manager, please.','colleague|colega|KA-liig|He is my colleague.','meeting|reunião|MII-ting|The meeting starts now.'],['What do you do?','I work in an office.','I have a meeting at ten.']],
  ['transport','Transportation','Escolher transportes e falar sobre deslocamentos.',['bus|ônibus|bas|The bus is crowded.','train|trem|trein|Our train leaves soon.','car|carro|kar|Her car is blue.','bicycle|bicicleta|BAI-si-kəl|I ride my bicycle.','ticket|passagem|TI-kit|One ticket, please.','airport|aeroporto|ER-port|The airport is far.','stop|parada|stap|Get off at the next stop.','drive|dirigir|draiv|Can you drive?'],['Where is the bus stop?','I need a return ticket.','The train leaves at eight.']],
  ['health','Health and Emergencies','Comunicar sintomas e pedir ajuda em emergências.',['help|ajuda|help|Help me, please!','pain|dor|pein|I have pain here.','sick|doente|sik|He feels sick today.','medicine|remédio|MED-i-sin|Take this medicine.','doctor|médico(a)|DAK-tər|I need a doctor.','emergency|emergência|i-MER-jən-si|This is an emergency.','ambulance|ambulância|AM-byu-ləns|Call an ambulance!','allergy|alergia|AL-ər-dji|I have a food allergy.'],['I need help now.','Where is the nearest hospital?','I am allergic to nuts.']],
  ['final','A1 Final Challenge','Integrar vocabulário e comunicação A1 em situações reais.',['introduce|apresentar|in-trə-DUUS|Let me introduce myself.','choose|escolher|tchuuz|Choose the best answer.','explain|explicar|ik-SPLEIN|Please explain the problem.','understand|entender|an-dər-STÆND|I understand the question.','repeat|repetir|ri-PIIT|Could you repeat that?','answer|resposta|AN-sər|Check your answer.','ready|pronto(a)|RE-di|I am ready to begin.','complete|completar|kəm-PLIIT|Complete the final challenge.'],['Could you repeat that, please?','I can handle everyday situations.','I am ready for the challenge.']]
].map((row,index)=>({id:row[0],title:row[1],objective:row[2],vocab:row[3].map(v=>{const [word,translation,pronunciation,example]=v.split('|');return {word,translation,pronunciation,example}}),phrases:row[4],minutes:18,xp:index===14?150:60+(index%3)*10,test:(index+1)%5===0||index===14}));
window.A1_LESSONS=A1_LESSONS;
